import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { CategloryProvider } from '@/context/CategloryContext';
import { ConfigProvider } from 'antd';
import thTH from 'antd/locale/th_TH'; // ถ้าใช้ภาษาไทย

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          locale={thTH}
          theme={{
            components: {
              Tabs: {
          itemActiveColor: 'black',
          inkBarColor: '#D7284E',
          colorPrimary: 'black',
              },
            },
          }}
        >
          <CategloryProvider>{children}</CategloryProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
