import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { CategloryProvider } from '@/context/CategloryContext';
import { ConfigProvider } from 'antd';
import thTH from 'antd/locale/th_TH';
import { Kanit } from 'next/font/google';
import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const kanit = Kanit({
  weight: ['100', '200', '300', '400', '500', '700', '800'],
  subsets: ['thai'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Roi Raeng Restaurant',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kanit.className}`}
      >
        <ConfigProvider
          locale={thTH}
          theme={{
            token: {
              fontFamily: 'Kanit, sans-serif',
            },
            components: {
              Tabs: {
                itemActiveColor: 'black',
                inkBarColor: '#D7284E',
                colorPrimary: 'black',
              },
            },
          }}
        >
          <CategloryProvider>
            <Providers>
              <CategloryProvider>{children}</CategloryProvider>
            </Providers>
          </CategloryProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
